require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CorpusLeadsController do

  # This should return the minimal set of attributes required to create a valid
  # CorpusLead. As you add validations to CorpusLead, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "tweet" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CorpusLeadsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all corpus_leads as @corpus_leads" do
      corpus_lead = CorpusLead.create! valid_attributes
      get :index, {}, valid_session
      assigns(:corpus_leads).should eq([corpus_lead])
    end
  end

  describe "GET show" do
    it "assigns the requested corpus_lead as @corpus_lead" do
      corpus_lead = CorpusLead.create! valid_attributes
      get :show, {:id => corpus_lead.to_param}, valid_session
      assigns(:corpus_lead).should eq(corpus_lead)
    end
  end

  describe "GET new" do
    it "assigns a new corpus_lead as @corpus_lead" do
      get :new, {}, valid_session
      assigns(:corpus_lead).should be_a_new(CorpusLead)
    end
  end

  describe "GET edit" do
    it "assigns the requested corpus_lead as @corpus_lead" do
      corpus_lead = CorpusLead.create! valid_attributes
      get :edit, {:id => corpus_lead.to_param}, valid_session
      assigns(:corpus_lead).should eq(corpus_lead)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CorpusLead" do
        expect {
          post :create, {:corpus_lead => valid_attributes}, valid_session
        }.to change(CorpusLead, :count).by(1)
      end

      it "assigns a newly created corpus_lead as @corpus_lead" do
        post :create, {:corpus_lead => valid_attributes}, valid_session
        assigns(:corpus_lead).should be_a(CorpusLead)
        assigns(:corpus_lead).should be_persisted
      end

      it "redirects to the created corpus_lead" do
        post :create, {:corpus_lead => valid_attributes}, valid_session
        response.should redirect_to(CorpusLead.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved corpus_lead as @corpus_lead" do
        # Trigger the behavior that occurs when invalid params are submitted
        CorpusLead.any_instance.stub(:save).and_return(false)
        post :create, {:corpus_lead => { "tweet" => "invalid value" }}, valid_session
        assigns(:corpus_lead).should be_a_new(CorpusLead)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CorpusLead.any_instance.stub(:save).and_return(false)
        post :create, {:corpus_lead => { "tweet" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested corpus_lead" do
        corpus_lead = CorpusLead.create! valid_attributes
        # Assuming there are no other corpus_leads in the database, this
        # specifies that the CorpusLead created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CorpusLead.any_instance.should_receive(:update_attributes).with({ "tweet" => "MyString" })
        put :update, {:id => corpus_lead.to_param, :corpus_lead => { "tweet" => "MyString" }}, valid_session
      end

      it "assigns the requested corpus_lead as @corpus_lead" do
        corpus_lead = CorpusLead.create! valid_attributes
        put :update, {:id => corpus_lead.to_param, :corpus_lead => valid_attributes}, valid_session
        assigns(:corpus_lead).should eq(corpus_lead)
      end

      it "redirects to the corpus_lead" do
        corpus_lead = CorpusLead.create! valid_attributes
        put :update, {:id => corpus_lead.to_param, :corpus_lead => valid_attributes}, valid_session
        response.should redirect_to(corpus_lead)
      end
    end

    describe "with invalid params" do
      it "assigns the corpus_lead as @corpus_lead" do
        corpus_lead = CorpusLead.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CorpusLead.any_instance.stub(:save).and_return(false)
        put :update, {:id => corpus_lead.to_param, :corpus_lead => { "tweet" => "invalid value" }}, valid_session
        assigns(:corpus_lead).should eq(corpus_lead)
      end

      it "re-renders the 'edit' template" do
        corpus_lead = CorpusLead.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CorpusLead.any_instance.stub(:save).and_return(false)
        put :update, {:id => corpus_lead.to_param, :corpus_lead => { "tweet" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested corpus_lead" do
      corpus_lead = CorpusLead.create! valid_attributes
      expect {
        delete :destroy, {:id => corpus_lead.to_param}, valid_session
      }.to change(CorpusLead, :count).by(-1)
    end

    it "redirects to the corpus_leads list" do
      corpus_lead = CorpusLead.create! valid_attributes
      delete :destroy, {:id => corpus_lead.to_param}, valid_session
      response.should redirect_to(corpus_leads_url)
    end
  end

end
